### ISSUE TITLE
Relative imports are not supported with Max's implementation of require() 

### ISSUE THREAD

**Issue by dan-reid** [ErnstHot/TypeScript-for-Max#25] opened 2021-11-29 00:46 UTC
HI, I tried out the included examples but I get the errors below:

```
js: error calling function msg_float [ExampleJS]
js: ExampleJS: Javascript TypeError: em.square is not a function, line 16
``` 

However, if I go into the complied file: `JavaScript/ExampleJS.js` and update `var em = require("./ExampleModule");` to `var em = require("ExampleModule");` it works. 

For single scripts I guess this is a workable solution but not for anything more complex. Was wondering if there are any work arounds? 

```
Max: 8.2.1
tsc: 4.5.2
```

**Comment by dan-reid** [comment] 2021-11-29 22:38
@VulumeCode I'm on macOS 11.6. I'd be surprised if that was it though. 

Are you moving the JavaScript directory to any special location before opening it?

**Comment by VulumeCode** [comment] 2021-11-30 10:06
No, they just have to all be in the same directory as the .maxpat. It works immediately after cloning the repo.

I believe the Max guys implemented their own JS engine based on the ES3 standard back then. Dunno what OS quirks they worked in. It's a huge lucky coincidence that a nice language like TS even compiles to ES3.

I hope you find the cause. As a workaround though maybe you can make a build script that runs a find & replace command after tsc. It's a strict pattern after all, shouldn't be too messy.

**Comment by dan-reid** [comment] 2021-12-01 00:39
Out of interest, what OS are you on? I guess it may be the cause but it would seem strange to me if their implementation of something as fundamental as `require` was affected by OS. It would definitely reduce the portability of max patches. 

Also, the [examples in the docs](https://docs.cycling74.com/max8/vignettes/jsrequire) use the filename only, without any relative or absolute paths. Though they don't comment on whether it's the only supported format. Evidentially it's not, but it would have been nice if they provided a little more info.

Writing a script to fix the pathnames would probably work but I'm not sure I want to resort to that. I don't necessarily need to run my code in directly max for the project I'm working on, it just would have been a little cleaner to do it that way.    

Anyway, thanks for getting back to me.

**Comment by VulumeCode** [comment] 2021-12-01 11:45
I'm on Windows. In the end I decided on writing C externals for my sequencer, so I never ran into protability issues.

Filename only works just the same for me.  I guess that's why the problem didn't pop up earlier for JS coders.

**Comment by dan-reid** [comment] 2021-12-01 23:42
Okay, thanks. Yeah, It would be great if they addressed it. Support for relative paths on windows and mac seems a fairly reasonable expectation. I wonder if it is just a bug or a 'feature' they worked in.

**Comment by twhiston** [comment] 2023-04-26 15:39
Just to comment and close this. Currently today you still need to use `var em = require("ExampleModule");` instead of `var em = require("./ExampleModule");` and the examples have been updated to reflect this in #27 and I've added some commentary to the README discussing this too.

For bigger projects you can always do path rewrites as needed in your `tsconfig.js` file which help address this, and I've done this extensively with success to load local Typescript in subfolders. ie.

```json
"paths": {
      "Cursor": [
        "Cursor/Cursor"
      ]
}
```
When you do this Typescript will transpile the requires correctly, omitting the `./`

**Closed by twhiston** 2023-04-26 15:39 UTC
